FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV DATABASE_URL=postgresql://postgres:postgres@postgres:5432/notifyflow

RUN npx prisma generate

CMD ["npm", "run", "dev"]